rasplit <- seq(0, 360, length.out = 9)

decsplit <- seq(-40, 80, length.out = 9)

lctrendtest_p1a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p2a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p3a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p4a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p5a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p6a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p7a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p8a <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[1] & as.numeric(as.vector(objdatset$DEC)) < decsplit[2]),]), 1000),], bins = 56000)

lctrendtest_p1b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p2b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p3b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p4b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p5b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p6b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p7b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p8b <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[2] & as.numeric(as.vector(objdatset$DEC)) < decsplit[3]),]), 1000),], bins = 56000)

lctrendtest_p1c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p2c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p3c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p4c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p5c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p6c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p7c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p8c <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[3] & as.numeric(as.vector(objdatset$DEC)) < decsplit[4]),]), 1000),], bins = 56000)

lctrendtest_p1d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p2d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p3d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p4d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p5d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p6d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p7d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p8d <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[4] & as.numeric(as.vector(objdatset$DEC)) < decsplit[5]),]), 1000),], bins = 56000)

lctrendtest_p1e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p2e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p3e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p4e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p5e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p6e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p7e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p8e <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[5] & as.numeric(as.vector(objdatset$DEC)) < decsplit[6]),]), 1000),], bins = 56000)

lctrendtest_p1f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p2f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p3f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p4f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p5f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p6f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p7f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p8f <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[6] & as.numeric(as.vector(objdatset$DEC)) < decsplit[7]),]), 1000),], bins = 56000)

lctrendtest_p1g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p2g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p3g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p4g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p5g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p6g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p7g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p8g <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[7] & as.numeric(as.vector(objdatset$DEC)) < decsplit[8]),]), 1000),], bins = 56000)

lctrendtest_p1h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[1] & as.numeric(as.vector(objdatset$RA)) < rasplit[2] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p2h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[2] & as.numeric(as.vector(objdatset$RA)) < rasplit[3] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p3h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[3] & as.numeric(as.vector(objdatset$RA)) < rasplit[4] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p4h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[4] & as.numeric(as.vector(objdatset$RA)) < rasplit[5] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p5h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[5] & as.numeric(as.vector(objdatset$RA)) < rasplit[6] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p6h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[6] & as.numeric(as.vector(objdatset$RA)) < rasplit[7] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p7h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[7] & as.numeric(as.vector(objdatset$RA)) < rasplit[8] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)

lctrendtest_p8h <- lctrendtrain(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),][sample(1:nrow(objdatset[which(as.numeric(as.vector(objdatset$RA)) > rasplit[8] & as.numeric(as.vector(objdatset$RA)) < rasplit[9] & as.numeric(as.vector(objdatset$DEC)) > decsplit[8] & as.numeric(as.vector(objdatset$DEC)) < decsplit[9]),]), 1000),], bins = 56000)